name: deploy

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_PACKAGE_PATH: './build'
  NODE_VERSION: '12.13.0'
  AZURE_WEBAPP_NAME: 'realworld-demo-blog'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: NPM build
        run: |
          npm install
          npm run build
  
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
